@url = http://localhost:5000/users-module 
@email = gwalus1404@gmail.com
@password = password 
@role = user 
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYjY2MTk2MC0zYmMxLTRlYTktYjc2YS0wYWI5Y2FhMzljYjkiLCJ1bmlxdWVfbmFtZSI6ImZiNjYxOTYwLTNiYzEtNGVhOS1iNzZhLTBhYjljYWEzOWNiOSIsImp0aSI6ImEzMTM1NjQxLWIzYzAtNDg0OS04YjUwLTVhOTc2YjZmYmQwOCIsImlhdCI6IjE2OTAzODEyNjcyMjYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidXNlcnMiLCJ0aWNrZXRzIl0sIm5iZiI6MTY5MDM4MTI2NywiZXhwIjoxNjkwNDE3MjY3LCJpc3MiOiJjb25mYWIifQ.3oNv8lFwU3nBp6p327JH3PLrF2U6WAz-bNgALbAOv0M

### 
GET {{url}}

###
GET {{url}}/account 
Authorization: Bearer {{accessToken}}

###
POST {{url}}/account/sign-up 
Content-Type: application/json

{
    "email": "{{email}}", 
    "password": "{{password}}", 
    "role": "{{role}}", 
    "claims": 
    {
        "permissions": 
        [
            "conferences", "hosts", "speakers", "users", "tickets"
        ]
    }
}

###
POST {{url}}/account/sign-in 
Content-Type: application/json

{
    "email": "{{email}}", 
    "password": "{{password}}"
}