@url = http://localhost:5000/users-module 
@email = gwalus1404@gmail.com
@password = password 
@role = user 
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYjY2MTk2MC0zYmMxLTRlYTktYjc2YS0wYWI5Y2FhMzljYjkiLCJ1bmlxdWVfbmFtZSI6ImZiNjYxOTYwLTNiYzEtNGVhOS1iNzZhLTBhYjljYWEzOWNiOSIsImp0aSI6IjM3NmRmOTg5LTlkMGQtNGVlYS1iNjRjLWRjYWM0MzdkZmI4MCIsImlhdCI6IjE2OTA0NDc4NjI1NzEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidXNlcnMiLCJ0aWNrZXRzIl0sIm5iZiI6MTY5MDQ0Nzg2MiwiZXhwIjoxNjkwNDgzODYyLCJpc3MiOiJjb25mYWIifQ.3Sj6NR14QsZDY8lLvRSFGBhtKw3dY84J0wsultIXTxE

### 
GET {{url}}

###
GET {{url}}/account 
Authorization: Bearer {{accessToken}}

###
POST {{url}}/account/sign-up 
Content-Type: application/json

{
    "email": "{{email}}", 
    "password": "{{password}}", 
    "role": "{{role}}", 
    "claims": 
    {
        "permissions": 
        [
            "conferences", "hosts", "speakers", "users", "tickets"
        ]
    }
}

###
POST {{url}}/account/sign-in 
Content-Type: application/json

{
    "email": "{{email}}", 
    "password": "{{password}}"
}