@url = http://localhost:5000/conferences-module

@hostId = b44f89d1-7d20-49a0-8d58-363e05909e1f

@conferenceId = 5e4a7c0b-de90-4a6c-b968-55ac34946717

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYWUwNjEwMy02OThmLTRlZjUtOTg2OC04NzZhMjJkNDUyODQiLCJ1bmlxdWVfbmFtZSI6ImJhZTA2MTAzLTY5OGYtNGVmNS05ODY4LTg3NmEyMmQ0NTI4NCIsImp0aSI6IjgwZDA0ZDI5LWFmOTEtNGU1MC05MDM4LTcxYWI1YzE0NWRlMyIsImlhdCI6IjE2NzQ0OTg3NDUxNDUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidXNlcnMiLCJ0aWNrZXRzIl0sIm5iZiI6MTY3NDQ5ODc0NSwiZXhwIjoxNjc0NTM0NzQ1LCJpc3MiOiJjb25mYWIifQ.I-8yPwy9y4TcXnLpCXAypzrnj8KTOSzGmmgA6ADiyKU
###
GET {{url}}

###
POST {{url}}/hosts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "host #1",
    "description": "lorem ipsum"
}

###
GET {{url}}/hosts

###
GET {{url}}/hosts/{{hostId}}

###
PUT {{url}}/hosts/{{hostId}}
Content-Type: application/json

{
    "name": "host #2",
    "description": "lorem ipsum 2"
}

###
DELETE  {{url}}/hosts/{{hostId}}

###
POST {{url}}/conferences
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "hostId": "{{hostId}}",
    "name": "host #1",
    "description": "lorem ipsum",
    "location": "testas",
    "from": "2022-05-01",
    "to": "2022-05-04",
    "participantsLimit": "100",
    "logoUrl": null
}

###
GET {{url}}/conferences

###
GET {{url}}/conferences/{{conferenceId}} 

###
PUT {{url}}/conferences/{{conferenceId}}
Content-Type: application/json

{
    "name": "conference #2",
    "description": "lorem ipsum 2",    
    "location": "testas",
    "from": "2022-05-01",
    "to": "2022-05-04",
    "participantsLimit": "100",
    "logoUrl": null
}

###
DELETE  {{url}}/conferences/{{conferenceId}}