@url = http://localhost:5000/conferences-module

@hostId = 7b5e5f82-8d88-4bb9-b561-65e605c7a85f

@conferenceId = 5e4a7c0b-de90-4a6c-b968-55ac34946717

###
GET {{url}}

###
POST {{url}}/hosts
Content-Type: application/json

{
    "name": "host #1",
    "description": "lorem ipsum"
}

###
GET {{url}}/hosts

###
GET {{url}}/hosts/{{hostId}}

###
PUT {{url}}/hosts/{{hostId}}
Content-Type: application/json

{
    "name": "host #2",
    "description": "lorem ipsum 2"
}

###
DELETE  {{url}}/hosts/{{hostId}}

###
POST {{url}}/conferences
Content-Type: application/json

{
    "hostId": "{{hostId}}",
    "name": "host #1",
    "description": "lorem ipsum",
    "location": "testas",
    "from": "2022-05-01",
    "to": "2022-05-04",
    "participantsLimit": "100",
    "logoUrl": null
}

###
GET {{url}}/conferences

###
GET {{url}}/conferences/{{conferenceId}} 

###
PUT {{url}}/conferences/{{conferenceId}}
Content-Type: application/json

{
    "name": "conference #2",
    "description": "lorem ipsum 2",    
    "location": "testas",
    "from": "2022-05-01",
    "to": "2022-05-04",
    "participantsLimit": "100",
    "logoUrl": null
}

###
DELETE  {{url}}/conferences/{{conferenceId}}