@url = http://localhost:5000/conferences-module

@hostId = 75fb4c1f-2083-4bc6-9e61-d4cd8bd62d0b

@conferenceId = 629b3d90-a0d7-4a6d-bc5b-405be2ba23dd

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYjY2MTk2MC0zYmMxLTRlYTktYjc2YS0wYWI5Y2FhMzljYjkiLCJ1bmlxdWVfbmFtZSI6ImZiNjYxOTYwLTNiYzEtNGVhOS1iNzZhLTBhYjljYWEzOWNiOSIsImp0aSI6ImEzMTM1NjQxLWIzYzAtNDg0OS04YjUwLTVhOTc2YjZmYmQwOCIsImlhdCI6IjE2OTAzODEyNjcyMjYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidXNlcnMiLCJ0aWNrZXRzIl0sIm5iZiI6MTY5MDM4MTI2NywiZXhwIjoxNjkwNDE3MjY3LCJpc3MiOiJjb25mYWIifQ.3oNv8lFwU3nBp6p327JH3PLrF2U6WAz-bNgALbAOv0M
###
GET {{url}}

###
POST {{url}}/hosts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "ABC Company",
    "description": "This company provides a .NET Cources from stratch to advanced."
}

###
GET {{url}}/hosts

###
GET {{url}}/hosts/{{hostId}}

###
PUT {{url}}/hosts/{{hostId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "GW Company",
    "description": "This company provides a .NET Cources from stratch to advanced."
}

###
DELETE  {{url}}/hosts/7b0d6fb2-5e9f-45c6-b6b9-f7a6ac8a00c2
Authorization: Bearer {{accessToken}}

###
POST {{url}}/conferences
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "hostId": "{{hostId}}",
    "name": "C# Good practices",
    "description": "Design Patterns",
    "location": "online",
    "from": "2023-12-01",
    "to": "2023-12-10",
    "participantsLimit": "300",
    "logoUrl": null
}

###
GET {{url}}/conferences

###
GET {{url}}/conferences/{{conferenceId}} 

###
PUT {{url}}/conferences/{{conferenceId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "hostId": "{{hostId}}",
    "name": "C# Fundamentals course",
    "description": "From basic functions to build an app with WindowsForms and WPF.",
    "location": "online",
    "from": "2023-11-01",
    "to": "2023-11-10",
    "participantsLimit": "400",
    "logoUrl": null
}

###
DELETE  {{url}}/conferences/{{conferenceId}}